# Generated by Django 4.2.4 on 2023-08-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='resim',
            field=models.CharField(default='10.jpg', max_length=100),
        ),
    ]
