# Generated by Django 4.2.4 on 2023-08-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_uploadmodel_remove_adviser_resim_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
