# Generated by Django 4.2.4 on 2023-09-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_uploadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.blog')),
            ],
        ),
    ]
